# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{computation}
  s.version = "0.0.8"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andy Rossmeissl", "Seamus Abshere", "Ian Hough", "Matt Kling", "Derek Kastner"]
  s.date = %q{2010-12-22}
  s.description = %q{A software model in Ruby for the greenhouse gas emissions of a computer's computations}
  s.email = %q{andy@rossmeissl.net}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "lib/computation.rb",
    "lib/computation/carbon_model.rb",
    "lib/computation/characterization.rb",
    "lib/computation/data.rb",
    "lib/computation/fallback.rb",
    "lib/computation/relationships.rb",
    "lib/computation/summarization.rb",
    "lib/test_support/computation_record.rb"
  ]
  s.homepage = %q{http://github.com/brighterplanet/computation}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A carbon model}
  s.test_files = [
    "features/computation_committees.feature",
    "features/computation_emissions.feature",
    "features/support/env.rb",
    "lib/test_support/computation_record.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<sniff>, ["~> 0.4.9"])
      s.add_runtime_dependency(%q<emitter>, ["~> 0.3"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<emitter>, ["~> 0.3"])
      s.add_dependency(%q<sniff>, ["~> 0.4.9"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<emitter>, ["~> 0.3"])
    s.add_dependency(%q<sniff>, ["~> 0.4.9"])
  end
end

